server:
  port: 8001                # 指定该Eureka client实例的端口
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   #服务注册到eureka server的地址

spring:
  application:
    name: eureka-client2